### ISSUE TITLE
EPIC: Deployment and Documentation

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#13]
Prepare the application for a live environment, ensure security, and document the development and deployment processes.

#### Connected User Stories

* [x] [US: Document Deployment Process](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59345620)
* [x] [US: Secure Application for Deployment](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59210854)
* [x] [US: Prepare Application for Cloud Deployment](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59210783)
* [x] [US: Document Design and Development Process](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59210753)
