### ISSUE TITLE
US: Review LO in PP4 Assessment Material

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#14]
As a Developer, I can review Learning Objectives (LO) criteria in the PP4 Assessment Material so that I understand the project's requirements and success metrics.

#### Acceptance Criteria

* [x] The Learning Objectives (LO) criteria from the PP4 Assessment Material are comprehensively reviewed.
* [x] Key project requirements and success metrics defined by the LO criteria are documented.
* [x] LO criteria is used as a checklist for ongoing project assessment.

#### Tasks

* [x] Identify and compile all LO criteria mentioned in the PP4 Assessment Material.
* [x] Document the key project requirements and success metrics based on the LO criteria.
* [x] Create a detailed checklist of project requirements.

**Belonging to:** [EPIC - Initial Project Planning and Documentation](https://github.com/users/JaqiKal/projects/10/views/1?pane=issue&itemId=590101571)

**Comment by JaqiKal** [comment]
I use the Portfolio 4 Assessment Guide as requriement list for this project, and keep track by the user stories and by manually ticking of each LO.
