### ISSUE TITLE
US: Create Wireframe

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#18]
As a Developer, I can create a wireframe so that that there is a visual representation of the project's layout and functionality.

#### Acceptance Criteria
* [ ] The wireframe accurately represents the layout of the project.
* [ ] The wireframe includes key functionality and features as outlined in the project requirements.
* [ ] The finalized wireframe is added to the README.

#### Tasks
* [ ] Research and gather project requirements.
* [ ] Sketch initial wireframe designs based on requirements.
* [ ]  Implement basic wireframe using wireframing software.

**Belonging to:** [EPIC - Initial Project Planning and Documentation](https://github.com/users/JaqiKal/projects/10/views/1?pane=issue&itemId=590101571)
