### ISSUE TITLE
US: Edit Book Details

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#28]
As a user I want to edit the details of a book in my collection so that I can correct or update information.

#### Acceptance Criteria

* [x] Userz can select a book from their collection and access and edit form.
* [x] The edit form pre-populates with the book's existing details.
* [x] Update the book's details in the collection when the form is submitted

#### Tasks

* [x] Create an edit option for each book in the user's collection list.
* [x] Populate the edit form with the selected book's existing details.
* [x] Update the book's detsils in the collection when the form is submitted.

**Belonging to:** [EPIC - Book Management](url)
