### ISSUE TITLE
US: Create Error Handling Template

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#36]
Add a statement, following this format: "As a [role] I can [capability] so that [received_benefit/value]"

#### Acceptance Criteria

* [x] Create 403
* [x] Create 404
* [x] Create 500

#### Tasks
* [x]  Test that 403 is shown when triggered
* [x]  Test that 404 is shown when triggered
* [x]  Test that 500 is shown when triggered

**Belonging to:** [EPIC : Templates](https://github.com/users/JaqiKal/projects/10/views/1?pane=issue&itemId=59022305)
