### ISSUE TITLE
EPIC: User Authentication and Authorization

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#4]
Establish a secure user authentication and authorization framework allowing for sign-up, login/logout, and password resets.

#### Connected User Stories

* [x] [US: Sign Up for an Account](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59203390)
* [x] US: Log In and Out of the Application
* [x] [US: Reset Forgotten Password](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59205663)

**Comment by JaqiKal** [comment]
- In a deployed environment, following the steps to reset a forgotten password works until redirected from the reset email to the "Change Password" page. After entering and confirming the new password, the password is not changed. [US: Reset Forgotten Password](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59205663)

Pls see [Bug#61: BUG: Change password does not work] (https://github.com/users/JaqiKal/projects/10/views/1?pane=issue&itemId=62030839)

**Comment by JaqiKal** [comment]
Solved by resetting template password_reset_from_key.html to its origin. Something in my customized template did not redirect to password_reset_done.
