### ISSUE TITLE
EPIC:  Book Management

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/ScrollStack#5]
To enable users to comprehensively manage their book collections through functionalities that allow adding, viewing, editing, and deleting books. This feature aims to provide users with a personalized and easily accessible catalog of the books they own or have read.

#### Connected User Stories
* [x] [US: Add New Books to Collection](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59206611)
* [x] [US: View List of Books](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59207220)
* [x] [US: Edit Book Details](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59210730)
* [x] [US: Delete a Book](https://github.com/users/JaqiKal/projects/10/views/6?pane=issue&itemId=59211047)
